name: "Build Release Docker"
on:
  release:
    types:
      - created
jobs:
  build-crossplatform:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup QEMU"
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "all"
      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v3
      - name: "Login to Dockerhub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_KEY }}
      - name: "Build and push"
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            abelodev/static-exporter:${{ github.event.release.tag_name }}
          platforms: linux/amd64, linux/arm64, windows/amd64
