name: "Build Release Binaries"
on:
  release:
    types:
      - created

jobs:
  compile-binaries:
    name: "Compile release binaries"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
      - name: "Setup Go"
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.23.2
      - name: "Compile binaries"
        run: bash build.sh ${{ github.event.release.tag_name }}
      - name: "Upload binaries"
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: '${{ github.token }}'
          tag: '${{ github.ref }}'
          file: ./release/static-exporter-*
          file_glob: true
