name: "Build Release Binaries"
on:
  release:
    types:
      - created
jobs:
  build:
    name: "Build Release Assets"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Setup Go"
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.23.2

      - name: "Display Go version"
        run: go version

      - name: "Display the release tag"
        run: echo ${{ github.event.release.tag_name }}